//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unvell.D2DLib.Examples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unvell.D2DLib.Examples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_car_production_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_car_production_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_himeji_castle_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_himeji_castle_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_home_page_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_home_page_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_music_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_music_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_uwu_emoji_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_uwu_emoji_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IMGP6873 {
            get {
                object obj = ResourceManager.GetObject("IMGP6873", resourceCulture);
                return ((byte[])(obj));
            }
        }

		/// <summary>
		///   Looks up a localized resource of type System.Byte[].
		/// </summary>
		internal static System.Drawing.Bitmap Flowers
		{
			get
			{
				object obj = ResourceManager.GetObject("Flowers", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		/// <summary>
		///   Looks up a localized resource of type System.Byte[].
		/// </summary>
		internal static byte[] space_bg {
            get {
                object obj = ResourceManager.GetObject("space_bg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A long time ago, in a galaxy far, far away....
        ///
        ///It is a period of civil war. Rebel
        ///spaceships, striking from a hidden
        ///base, have won their first victory
        ///against the evil Galactic Empire.
        ///
        ///During the battle, rebel spies managed
        ///to steal secret plans to the Empire&apos;s
        ///ultimate weapon, the Death Star, an
        ///armored space station with enough
        ///power to destroy an entire planet.
        ///
        ///Pursued by the Empire&apos;s sinister agents,
        ///Princess Leia races home aboard her
        ///starship, custodian of the stolen plans
        ///that can [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Star_Subtitle_Original {
            get {
                return ResourceManager.GetString("Star_Subtitle_Original", resourceCulture);
            }
        }
    }
}
